const { v4: uuidv4 } = require('uuid');
const { format, addDays, parseISO, differenceInDays } = require('date-fns');
const _ = require('lodash');
const tidpService = require('./tidpService');

class MIDPService {
  constructor() {
    this.midps = new Map();
  }

  /**
   * Auto-generate MIDP from all TIDPs in a project
   * @param {string} projectId - Project ID
   * @param {Object} midpData - Basic MIDP information
   * @returns {Object} Generated MIDP
   */
  autoGenerateMIDPFromProject(projectId, midpData = {}) {
    const allTidps = tidpService.getTIDPsByProject(projectId);

    if (allTidps.length === 0) {
      throw new Error(`No TIDPs found for project ${projectId}`);
    }

    const tidpIds = allTidps.map(t => t.id);

    const midp = {
      id: uuidv4(),
      projectName: midpData.projectName || `Project ${projectId}`,
      description: midpData.description || `Auto-generated MIDP from ${allTidps.length} TIDPs`,
      projectId,
      includedTIDPs: tidpIds,
      aggregatedData: this.aggregateTIDPs(allTidps),
      deliverySchedule: this.generateDeliverySchedule(allTidps),
      riskRegister: this.consolidateRisks(allTidps),
      dependencyMatrix: this.generateDependencyMatrixFromTIDPs(allTidps),
      resourcePlan: this.generateResourcePlan(allTidps),
      qualityGates: this.defineQualityGates(allTidps),
      evolutionHistory: this.createEvolutionSnapshot(allTidps),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: '1.0',
      status: 'Active',
      autoGenerated: true
    };

    this.midps.set(midp.id, midp);
    return midp;
  }

  /**
   * Create MIDP by aggregating TIDPs (legacy - for backward compatibility)
   * @param {Object} midpData - Basic MIDP information
   * @param {Array} tidpIds - Array of TIDP IDs to include
   * @returns {Object} Generated MIDP
   */
  createMIDPFromTIDPs(midpData, tidpIds) {
    const tidps = tidpIds.map(id => tidpService.getTIDP(id));

    const midp = {
      id: uuidv4(),
      ...midpData,
      includedTIDPs: tidpIds,
      aggregatedData: this.aggregateTIDPs(tidps),
      deliverySchedule: this.generateDeliverySchedule(tidps),
      riskRegister: this.consolidateRisks(tidps),
      dependencyMatrix: this.generateDependencyMatrixFromTIDPs(tidps),
      resourcePlan: this.generateResourcePlan(tidps),
      qualityGates: this.defineQualityGates(tidps),
      evolutionHistory: this.createEvolutionSnapshot(tidps),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: '1.0',
      status: 'Active'
    };

    this.midps.set(midp.id, midp);
    return midp;
  }

  /**
   * Update MIDP with new TIDP data
   * @param {string} midpId - MIDP ID
   * @param {Array} updatedTidpIds - Updated TIDP IDs
   * @returns {Object} Updated MIDP
   */
  updateMIDPFromTIDPs(midpId, updatedTidpIds) {
    const existingMidp = this.midps.get(midpId);
    if (!existingMidp) {
      throw new Error(`MIDP with ID ${midpId} not found`);
    }

    const tidps = updatedTidpIds.map(id => tidpService.getTIDP(id));

    const updatedMidp = {
      ...existingMidp,
      includedTIDPs: updatedTidpIds,
      aggregatedData: this.aggregateTIDPs(tidps),
      deliverySchedule: this.generateDeliverySchedule(tidps),
      riskRegister: this.consolidateRisks(tidps),
      dependencyMatrix: this.generateDependencyMatrixFromTIDPs(tidps),
      resourcePlan: this.generateResourcePlan(tidps),
      updatedAt: new Date().toISOString(),
      version: this.incrementVersion(existingMidp.version)
    };

    this.midps.set(midpId, updatedMidp);
    return updatedMidp;
  }

  /**
   * Aggregate TIDP data into consolidated format
   * @param {Array} tidps - Array of TIDP objects
   * @returns {Object} Aggregated data
   */
  aggregateTIDPs(tidps) {
    const containers = [];
    const milestones = new Map();
    const disciplines = new Set();
    const totalEstimatedHours = new Map();

    tidps.forEach(tidp => {
      disciplines.add(tidp.discipline);

      if (tidp.containers) {
        tidp.containers.forEach(container => {
          const aggregatedContainer = {
            id: container.id,
            name: container['Container Name'] || container.name,
            type: container.Type || container.type,
            format: container.Format || container.format,
            loiLevel: container['LOI Level'] || container.levelOfInformation,
            author: container.Author || container.author,
            tidpSource: {
              id: tidp.id,
              teamName: tidp.teamName,
              discipline: tidp.discipline
            },
            estimatedTime: container['Est. Time'] || container.estimatedProductionTime,
            milestone: container.Milestone || container.deliveryMilestone,
            dueDate: container['Due Date'] || container.dueDate,
            status: container.Status || container.status,
            dependencies: this.processDependencies(container.dependencies || [], tidps)
          };

          containers.push(aggregatedContainer);

          // Group by milestone
          const milestone = aggregatedContainer.milestone;
          if (milestone) {
            if (!milestones.has(milestone)) {
              milestones.set(milestone, {
                name: milestone,
                containers: [],
                teams: new Set(),
                earliestDate: aggregatedContainer.dueDate,
                latestDate: aggregatedContainer.dueDate,
                totalEstimatedHours: 0
              });
            }

            const ms = milestones.get(milestone);
            ms.containers.push(aggregatedContainer);
            ms.teams.add(tidp.teamName);

            // Update date range
            if (aggregatedContainer.dueDate) {
              if (!ms.earliestDate || aggregatedContainer.dueDate < ms.earliestDate) {
                ms.earliestDate = aggregatedContainer.dueDate;
              }
              if (!ms.latestDate || aggregatedContainer.dueDate > ms.latestDate) {
                ms.latestDate = aggregatedContainer.dueDate;
              }
            }

            // Add estimated hours
            const hours = this.parseTimeToHours(aggregatedContainer.estimatedTime);
            ms.totalEstimatedHours += hours;

            // Track by discipline
            const discipline = tidp.discipline;
            if (!totalEstimatedHours.has(discipline)) {
              totalEstimatedHours.set(discipline, 0);
            }
            totalEstimatedHours.set(discipline, totalEstimatedHours.get(discipline) + hours);
          }
        });
      }
    });

    return {
      containers,
      milestones: Array.from(milestones.values()).map(ms => ({
        ...ms,
        teams: Array.from(ms.teams),
        reviewDuration: this.calculateReviewDuration(ms.containers.length),
        riskLevel: this.assessMilestoneRisk(ms)
      })),
      disciplines: Array.from(disciplines),
      totalContainers: containers.length,
      totalEstimatedHours: Array.from(totalEstimatedHours.values()).reduce((sum, hours) => sum + hours, 0),
      estimatedHoursByDiscipline: Object.fromEntries(totalEstimatedHours)
    };
  }

  /**
   * Generate delivery schedule with critical path analysis
   * @param {Array} tidps - Array of TIDP objects
   * @returns {Object} Delivery schedule
   */
  generateDeliverySchedule(tidps) {
    const schedule = {
      phases: [],
      criticalPath: [],
      bufferAnalysis: {},
      recommendedSequence: []
    };

    // Extract all containers with dates
    const allContainers = [];
    tidps.forEach(tidp => {
      if (tidp.containers) {
        tidp.containers.forEach(container => {
          if (container['Due Date'] || container.dueDate) {
            allContainers.push({
              ...container,
              tidpId: tidp.id,
              teamName: tidp.teamName,
              discipline: tidp.discipline,
              dueDate: container['Due Date'] || container.dueDate
            });
          }
        });
      }
    });

    // Sort by due date
    allContainers.sort((a, b) => new Date(a.dueDate) - new Date(b.dueDate));

    // Group into phases (monthly)
    const phases = _.groupBy(allContainers, container => {
      const date = new Date(container.dueDate);
      return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
    });

    schedule.phases = Object.entries(phases).map(([period, containers]) => ({
      period,
      containerCount: containers.length,
      disciplines: _.uniq(containers.map(c => c.discipline)),
      totalEstimatedHours: containers.reduce((sum, c) =>
        sum + this.parseTimeToHours(c['Est. Time'] || c.estimatedProductionTime || '0'), 0
      ),
      containers: containers.map(c => ({
        id: c.id,
        name: c['Container Name'] || c.name,
        team: c.teamName,
        dueDate: c.dueDate
      }))
    }));

    // Identify critical path (simplified)
    schedule.criticalPath = this.identifyCriticalPath(allContainers);

    // Buffer analysis
    schedule.bufferAnalysis = this.analyzeBuffers(allContainers);

    return schedule;
  }

  /**
   * Consolidate risks from all TIDPs
   * @param {Array} tidps - Array of TIDP objects
   * @returns {Array} Consolidated risk register
   */
  consolidateRisks(tidps) {
    const risks = [];
    const riskCategories = new Map();

    tidps.forEach(tidp => {
      // Add TIDP-specific risks
      if (tidp.risks) {
        tidp.risks.forEach(risk => {
          risks.push({
            id: uuidv4(),
            ...risk,
            source: `TIDP: ${tidp.teamName}`,
            category: risk.category || 'Information Delivery'
          });
        });
      }

      // Analyze containers for potential risks
      if (tidp.containers) {
        tidp.containers.forEach(container => {
          // Dependency risks
          if (container.dependencies && container.dependencies.length > 2) {
            risks.push({
              id: uuidv4(),
              description: `High dependency count for ${container['Container Name'] || container.name}`,
              impact: 'Medium',
              probability: 'Medium',
              category: 'Dependency',
              mitigation: 'Review and simplify dependencies where possible',
              source: `Auto-detected from ${tidp.teamName}`,
              affectedContainer: container.id
            });
          }

          // Timeline risks
          if (container['Est. Time'] || container.estimatedProductionTime) {
            const hours = this.parseTimeToHours(container['Est. Time'] || container.estimatedProductionTime);
            if (hours > 200) { // More than 5 weeks
              risks.push({
                id: uuidv4(),
                description: `Extended timeline for ${container['Container Name'] || container.name}`,
                impact: 'High',
                probability: 'Medium',
                category: 'Schedule',
                mitigation: 'Consider breaking into smaller deliverables',
                source: `Auto-detected from ${tidp.teamName}`,
                affectedContainer: container.id
              });
            }
          }
        });
      }
    });

    // Categorize and prioritize risks
    risks.forEach(risk => {
      const category = risk.category || 'General';
      if (!riskCategories.has(category)) {
        riskCategories.set(category, []);
      }
      riskCategories.get(category).push(risk);
    });

    return {
      risks: risks.sort((a, b) => this.getRiskScore(b) - this.getRiskScore(a)),
      categories: Object.fromEntries(riskCategories),
      summary: {
        total: risks.length,
        high: risks.filter(r => r.impact === 'High').length,
        medium: risks.filter(r => r.impact === 'Medium').length,
        low: risks.filter(r => r.impact === 'Low').length
      }
    };
  }

  /**
   * Generate resource allocation plan
   * @param {Array} tidps - Array of TIDP objects
   * @returns {Object} Resource plan
   */
  generateResourcePlan(tidps) {
    const plan = {
      byDiscipline: {},
      byTimePeriod: {},
      peakUtilization: {},
      recommendations: []
    };

    tidps.forEach(tidp => {
      const discipline = tidp.discipline;

      if (!plan.byDiscipline[discipline]) {
        plan.byDiscipline[discipline] = {
          teams: 0,
          totalHours: 0,
          containers: 0,
          peakMonth: null,
          peakHours: 0
        };
      }

      plan.byDiscipline[discipline].teams += 1;

      if (tidp.containers) {
        plan.byDiscipline[discipline].containers += tidp.containers.length;

        tidp.containers.forEach(container => {
          const hours = this.parseTimeToHours(container['Est. Time'] || container.estimatedProductionTime || '0');
          plan.byDiscipline[discipline].totalHours += hours;

          // Track by time period
          const dueDate = container['Due Date'] || container.dueDate;
          if (dueDate) {
            const period = format(new Date(dueDate), 'yyyy-MM');

            if (!plan.byTimePeriod[period]) {
              plan.byTimePeriod[period] = {
                totalHours: 0,
                disciplines: new Set(),
                containers: 0
              };
            }

            plan.byTimePeriod[period].totalHours += hours;
            plan.byTimePeriod[period].disciplines.add(discipline);
            plan.byTimePeriod[period].containers += 1;
          }
        });
      }
    });

    // Convert sets to arrays
    Object.keys(plan.byTimePeriod).forEach(period => {
      plan.byTimePeriod[period].disciplines = Array.from(plan.byTimePeriod[period].disciplines);
    });

    // Identify peak utilization
    const periods = Object.entries(plan.byTimePeriod);
    if (periods.length > 0) {
      const peakPeriod = periods.reduce((max, [period, data]) =>
        data.totalHours > max[1].totalHours ? [period, data] : max
      );

      plan.peakUtilization = {
        period: peakPeriod[0],
        hours: peakPeriod[1].totalHours,
        disciplines: peakPeriod[1].disciplines.length
      };
    }

    // Generate recommendations
    plan.recommendations = this.generateResourceRecommendations(plan);

    return plan;
  }

  /**
   * Define quality gates based on aggregated information
   * @param {Array} tidps - Array of TIDP objects
   * @returns {Array} Quality gates
   */
  defineQualityGates(tidps) {
    const gates = [];
    const milestones = new Set();

    tidps.forEach(tidp => {
      if (tidp.containers) {
        tidp.containers.forEach(container => {
          const milestone = container.Milestone || container.deliveryMilestone;
          if (milestone) {
            milestones.add(milestone);
          }
        });
      }
    });

    milestones.forEach(milestone => {
      gates.push({
        id: uuidv4(),
        name: `Quality Gate: ${milestone}`,
        milestone,
        criteria: [
          'All information containers completed and validated',
          'Clash detection performed and conflicts resolved',
          'Model federation successful',
          'Quality assurance checks passed',
          'Client review and approval obtained'
        ],
        approvers: ['Information Manager', 'Project Director', 'Client Representative'],
        estimatedDuration: '1 week',
        dependencies: [`Completion of all ${milestone} deliverables`]
      });
    });

    return gates.sort((a, b) => a.milestone.localeCompare(b.milestone));
  }

  // Helper methods
  parseTimeToHours(timeString) {
    if (!timeString) return 0;

    const timeStr = timeString.toString().toLowerCase();

    if (timeStr.includes('week')) {
      const weeks = parseFloat(timeStr);
      return weeks * 40;
    } else if (timeStr.includes('day')) {
      const days = parseFloat(timeStr);
      return days * 8;
    } else if (timeStr.includes('hour')) {
      return parseFloat(timeStr);
    }

    return 0;
  }

  processDependencies(dependencies, allTidps) {
    return dependencies.map(depId => {
      const sourceTidp = allTidps.find(tidp =>
        tidp.containers && tidp.containers.some(c => c.id === depId)
      );

      if (sourceTidp) {
        const sourceContainer = sourceTidp.containers.find(c => c.id === depId);
        return {
          dependencyId: depId,
          sourceTeam: sourceTidp.teamName,
          sourceDiscipline: sourceTidp.discipline,
          sourceContainer: sourceContainer ? sourceContainer['Container Name'] || sourceContainer.name : 'Unknown',
          type: 'information'
        };
      }

      return {
        dependencyId: depId,
        type: 'external'
      };
    });
  }

  calculateReviewDuration(containerCount) {
    // Base 1 week + 1 day per 3 containers
    const baseDays = 5; // 1 week
    const additionalDays = Math.ceil(containerCount / 3);
    const totalDays = baseDays + additionalDays;

    return `${Math.ceil(totalDays / 5)} week${totalDays > 5 ? 's' : ''}`;
  }

  assessMilestoneRisk(milestone) {
    let riskLevel = 'Low';

    if (milestone.containers.length > 10) riskLevel = 'Medium';
    if (milestone.containers.length > 20) riskLevel = 'High';
    if (milestone.teams.length > 5) riskLevel = 'High';
    if (milestone.totalEstimatedHours > 500) riskLevel = 'High';

    return riskLevel;
  }

  identifyCriticalPath(containers) {
    // Simplified critical path identification
    // In production, implement proper CPM algorithm
    return containers
      .filter(c => c.dependencies && c.dependencies.length > 0)
      .map(c => c.id);
  }

  analyzeBuffers(containers) {
    // Simplified buffer analysis
    return {
      recommendedBuffer: '10%',
      criticalContainers: containers.filter(c => c.dependencies && c.dependencies.length > 2).length,
      averageLeadTime: '2 weeks'
    };
  }

  getRiskScore(risk) {
    const impactScore = { 'Low': 1, 'Medium': 2, 'High': 3, 'Critical': 4 };
    const probabilityScore = { 'Low': 1, 'Medium': 2, 'High': 3 };

    return (impactScore[risk.impact] || 1) * (probabilityScore[risk.probability] || 1);
  }

  generateResourceRecommendations(plan) {
    const recommendations = [];

    // Check for peak utilization
    if (plan.peakUtilization.hours > 400) {
      recommendations.push({
        type: 'workload',
        priority: 'High',
        message: `Peak utilization in ${plan.peakUtilization.period} requires resource balancing`,
        action: 'Consider redistributing workload or adding temporary resources'
      });
    }

    // Check discipline balance
    const disciplineHours = Object.values(plan.byDiscipline).map(d => d.totalHours);
    const maxHours = Math.max(...disciplineHours);
    const minHours = Math.min(...disciplineHours);

    if (maxHours > minHours * 3) {
      recommendations.push({
        type: 'balance',
        priority: 'Medium',
        message: 'Uneven workload distribution across disciplines',
        action: 'Review scope distribution and consider load balancing'
      });
    }

    return recommendations;
  }

  /**
   * Generate dependency matrix from TIDPs
   * @param {Array} tidps - Array of TIDP objects
   * @returns {Object} Dependency matrix
   */
  generateDependencyMatrixFromTIDPs(tidps) {
    const matrix = [];
    const summary = {
      totalDependencies: 0,
      criticalDependencies: 0,
      teamsInvolved: new Set()
    };

    tidps.forEach(tidp => {
      if (tidp.containers) {
        tidp.containers.forEach(container => {
          const dependencies = container.Dependencies || container.dependencies || [];

          dependencies.forEach(depId => {
            const dependencyTidp = tidps.find(t =>
              t.containers && t.containers.some(c => c.id === depId)
            );

            if (dependencyTidp) {
              const depContainer = dependencyTidp.containers.find(c => c.id === depId);

              matrix.push({
                from: {
                  tidpId: dependencyTidp.id,
                  tidpName: dependencyTidp.teamName,
                  containerId: depId,
                  containerName: depContainer ? (depContainer['Container Name'] || depContainer.name) : 'Unknown'
                },
                to: {
                  tidpId: tidp.id,
                  tidpName: tidp.teamName,
                  containerId: container.id,
                  containerName: container['Container Name'] || container.name
                },
                type: 'information_dependency',
                criticalPath: false // Simplified for now
              });

              summary.totalDependencies += 1;
              summary.teamsInvolved.add(tidp.teamName);
              summary.teamsInvolved.add(dependencyTidp.teamName);
            }
          });
        });
      }
    });

    summary.teamsInvolved = summary.teamsInvolved.size;

    return {
      matrix,
      summary
    };
  }

  incrementVersion(currentVersion) {
    const parts = currentVersion.split('.');
    const minor = parseInt(parts[1] || 0) + 1;
    return `${parts[0]}.${minor}.0`;
  }

  getMIDP(id) {
    const midp = this.midps.get(id);
    if (!midp) {
      throw new Error(`MIDP with ID ${id} not found`);
    }
    return midp;
  }

  getAllMIDPs() {
    return Array.from(this.midps.values());
  }

  deleteMIDP(id) {
    if (!this.midps.has(id)) {
      throw new Error(`MIDP with ID ${id} not found`);
    }
    return this.midps.delete(id);
  }

  /**
   * Create evolution snapshot for tracking MIDP changes over time
   * @param {Array} tidps - Array of TIDP objects
   * @returns {Object} Evolution snapshot
   */
  createEvolutionSnapshot(tidps) {
    const snapshot = {
      timestamp: new Date().toISOString(),
      tidpCount: tidps.length,
      totalContainers: 0,
      totalEstimatedHours: 0,
      deliverablesByMilestone: {},
      teamsByDiscipline: {},
      completionStatus: {
        planned: 0,
        inProgress: 0,
        completed: 0,
        delayed: 0
      }
    };

    tidps.forEach(tidp => {
      // Track teams by discipline
      if (!snapshot.teamsByDiscipline[tidp.discipline]) {
        snapshot.teamsByDiscipline[tidp.discipline] = 0;
      }
      snapshot.teamsByDiscipline[tidp.discipline] += 1;

      if (tidp.containers) {
        snapshot.totalContainers += tidp.containers.length;

        tidp.containers.forEach(container => {
          // Count total hours
          const hours = this.parseTimeToHours(container['Est. Time'] || container.estimatedProductionTime || '0');
          snapshot.totalEstimatedHours += hours;

          // Group by milestone
          const milestone = container.Milestone || container.deliveryMilestone || 'Unassigned';
          if (!snapshot.deliverablesByMilestone[milestone]) {
            snapshot.deliverablesByMilestone[milestone] = {
              count: 0,
              estimatedHours: 0,
              teams: new Set()
            };
          }
          snapshot.deliverablesByMilestone[milestone].count += 1;
          snapshot.deliverablesByMilestone[milestone].estimatedHours += hours;
          snapshot.deliverablesByMilestone[milestone].teams.add(tidp.teamName);

          // Track completion status
          const status = container.Status || container.status || 'Planned';
          const statusKey = status.toLowerCase().replace(' ', '');
          if (snapshot.completionStatus.hasOwnProperty(statusKey)) {
            snapshot.completionStatus[statusKey] += 1;
          } else {
            snapshot.completionStatus.planned += 1; // Default to planned
          }
        });
      }
    });

    // Convert sets to arrays
    Object.keys(snapshot.deliverablesByMilestone).forEach(milestone => {
      snapshot.deliverablesByMilestone[milestone].teams = Array.from(snapshot.deliverablesByMilestone[milestone].teams);
    });

    return snapshot;
  }

  /**
   * Get MIDP evolution over time
   * @param {string} midpId - MIDP ID
   * @returns {Object} Evolution data for dashboard
   */
  getMIDPEvolution(midpId) {
    const midp = this.getMIDP(midpId);

    // In a real implementation, this would fetch historical snapshots from database
    // For now, we return current state with placeholder historical data
    return {
      current: midp.evolutionHistory || this.createEvolutionSnapshot([]),
      historical: [
        // This would be populated from actual historical data
        {
          timestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
          tidpCount: Math.max(1, (midp.includedTIDPs?.length || 1) - 2),
          totalContainers: Math.max(1, (midp.aggregatedData?.totalContainers || 1) - 5),
          totalEstimatedHours: Math.max(100, (midp.aggregatedData?.totalEstimatedHours || 100) - 200)
        },
        {
          timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), // 15 days ago
          tidpCount: Math.max(1, (midp.includedTIDPs?.length || 1) - 1),
          totalContainers: Math.max(1, (midp.aggregatedData?.totalContainers || 1) - 2),
          totalEstimatedHours: Math.max(100, (midp.aggregatedData?.totalEstimatedHours || 100) - 100)
        }
      ]
    };
  }

  /**
   * Get deliverables dashboard data
   * @param {string} midpId - MIDP ID
   * @returns {Object} Dashboard data showing deliverables as spreadsheet rows
   */
  getDeliverablesDashboard(midpId) {
    const midp = this.getMIDP(midpId);
    const tidps = midp.includedTIDPs?.map(id => tidpService.getTIDP(id)) || [];

    const deliverables = [];

    tidps.forEach(tidp => {
      if (tidp.containers) {
        tidp.containers.forEach(container => {
          deliverables.push({
            id: container.id,
            containerName: container['Container Name'] || container.name,
            team: tidp.teamName,
            discipline: tidp.discipline,
            type: container.Type || container.type,
            format: container.Format || container.format,
            loiLevel: container['LOI Level'] || container.levelOfInformation,
            author: container.Author || container.author,
            estimatedTime: container['Est. Time'] || container.estimatedProductionTime,
            milestone: container.Milestone || container.deliveryMilestone,
            dueDate: container['Due Date'] || container.dueDate,
            status: container.Status || container.status,
            lastUpdated: tidp.updatedAt
          });
        });
      }
    });

    // Sort by due date
    deliverables.sort((a, b) => {
      const dateA = new Date(a.dueDate || '9999-12-31');
      const dateB = new Date(b.dueDate || '9999-12-31');
      return dateA - dateB;
    });

    return {
      deliverables,
      summary: {
        total: deliverables.length,
        byStatus: deliverables.reduce((acc, d) => {
          const status = d.status || 'Planned';
          acc[status] = (acc[status] || 0) + 1;
          return acc;
        }, {}),
        byMilestone: deliverables.reduce((acc, d) => {
          const milestone = d.milestone || 'Unassigned';
          acc[milestone] = (acc[milestone] || 0) + 1;
          return acc;
        }, {}),
        byDiscipline: deliverables.reduce((acc, d) => {
          acc[d.discipline] = (acc[d.discipline] || 0) + 1;
          return acc;
        }, {})
      }
    };
  }
}

module.exports = new MIDPService();